---

- name: Add rsyslog v8 repo
  become: yes
  apt_repository:
    repo: "ppa:adiscon/v8-stable"
    state: present
    update_cache: yes

- name: Purge old rsyslog config files leftover from upgrades
  become: yes
  file:
    path: "/etc/rsyslog.d/{{ item }}"
    state: absent
  with_items: "{{ sansible_rsyslog_config_files_to_purge }}"
  notify:
    - restart rsyslog

- name: Install rsyslog and supporting packages
  become: yes
  apt:
    name: "{{ item }}"
  with_items:
    - "libfastjson4={{ sansible_rsyslog_version_libfastjson4 }}"
    - "rsyslog={{ sansible_rsyslog_version }}"
    - "rsyslog-mmjsonparse={{ sansible_rsyslog_version_mmjsonparse }}"

- name: Configure default rsyslog shipping configs
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
  with_items:
    - rsyslog.conf
    - rsyslog.d/10-cloud-init-logs-shipping.conf
    - rsyslog.d/90-syslog-shipping.conf
  when: sansible_rsyslog_default_config
  notify:
    - restart rsyslog

- name: Configure Built-In Application Logs
  become: yes
  template:
    src: "{{ sansible_rsyslog_builtin_configs_application_logs_template.src }}"
    dest: "{{ sansible_rsyslog_builtin_configs_application_logs_template.dest }}"
  when: sansible_rsyslog_builtin_configs_application_logs_enabled
  notify:
    - restart rsyslog

- name: Configure Built-In Auth Logs
  become: yes
  template:
    src: "{{ sansible_rsyslog_builtin_configs_auth_logs_template.src }}"
    dest: "{{ sansible_rsyslog_builtin_configs_auth_logs_template.dest }}"
  when: sansible_rsyslog_builtin_configs_auth_logs_enabled
  notify:
    - restart rsyslog

- name: Configure Built-In Docker Application Logs
  become: yes
  template:
    src: "{{ sansible_rsyslog_builtin_configs_docker_application_logs_template.src }}"
    dest: "{{ sansible_rsyslog_builtin_configs_docker_application_logs_template.dest }}"
  when: sansible_rsyslog_builtin_configs_docker_application_logs_enabled
  notify:
    - restart rsyslog

- name: Configure Built-In Docker JSON Logs
  become: yes
  template:
    src: "{{ sansible_rsyslog_builtin_configs_docker_json_logs_template.src }}"
    dest: "{{ sansible_rsyslog_builtin_configs_docker_json_logs_template.dest }}"
  when: sansible_rsyslog_builtin_configs_docker_application_logs_enabled
  notify:
    - restart rsyslog

- name: Configure Built-In JSON Logs
  become: yes
  template:
    src: "{{ sansible_rsyslog_builtin_configs_json_logs_template.src }}"
    dest: "{{ sansible_rsyslog_builtin_configs_json_logs_template.dest }}"
  when: sansible_rsyslog_builtin_configs_json_logs_enabled
  notify:
    - restart rsyslog

- name: Configure Built-In nginx Logs
  become: yes
  template:
    src: "{{ sansible_rsyslog_builtin_configs_nginx_access_logs_template.src }}"
    dest: "{{ sansible_rsyslog_builtin_configs_nginx_access_logs_template.dest }}"
  when: sansible_rsyslog_builtin_configs_nginx_access_logs_enabled
  notify:
    - restart rsyslog
