---

- name: restart rsyslog
  become: yes
  service:
    name: rsyslog
    state: restarted

- name: start rsyslog
  become: yes
  service:
    name: rsyslog
    state: started

- name: stop rsyslog
  become: yes
  service:
    name: rsyslog
    state: stopped
