---

- name: Converge
  hosts: all
  gather_facts: yes

  roles:
    - role: rsyslog
      sansible_rsyslog_builtin_configs_auth_logs_enabled: yes
      sansible_rsyslog_builtin_configs_docker_application_logs_enabled: yes
      sansible_rsyslog_builtin_configs_docker_json_logs_enabled: yes
      sansible_rsyslog_builtin_configs_docker_journald_logs_enabled: yes
      sansible_rsyslog_builtin_configs_json_logs_enabled: yes
      sansible_rsyslog_builtin_configs_nginx_access_logs_enabled: yes
      sansible_rsyslog_config_global:
        maxMessageSize: 32K
      sansible_rsyslog_config_imfile:
        reopenOnTruncate: "off"
      sansible_rsyslog_config_main_queue:
        queue.size: 100000
      sansible_rsyslog_config_omfwd:
        action.resumeRetryCount: 10
